#
# Home Assistant Configuration for BresserWeatherSensorLW
#

# YAML anchors which can be used as aliases
ws_name: &ws_name "BresserWeatherSensorLW"
ws_device_id: &ws_device_id "ws-11c941"
ws_model: &ws_model "6-in-1"
ws_topic: &ws_topic "v3/YOUR_APPLICATION@ttn/devices/YOUR_DEVICE_EUI/up"
ws_expiry: &ws_expiry 1200

mqtt:    
  sensor:
    - name: "LoRaWAN Device Battery Voltage"
      unique_id: "{{ ws_device_id }}_voltage"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.a0_voltage_mv }}"
      device_class: "voltage"
      icon: "mdi:battery"
      unit_of_measurement: "mV"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
        
    # Weather Sensor
    - name: "Weather Sensor Battery o.k."
      unique_id: "{{ ws_device_id }}_battery"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.status.ws_batt_ok }}"
      device_class: "enum"
      icon: "mdi:battery"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Temperature"
      unique_id: "{{ ws_device_id }}_temp"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_temp_c }}"
      device_class: "temperature"
      unit_of_measurement: "째C"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Humidity"
      unique_id: "{{ ws_device_id }}_humidity"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_humidity }}"
      device_class: "humidity"
      unit_of_measurement: "%"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Wind Speed Gusts"
      unique_id: "{{ ws_device_id }}_wind_gusts"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_wind_gust_ms }}"
      device_class: "wind_speed"
      unit_of_measurement: "m/s"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Wind Speed Avg"
      unique_id: "{{ ws_device_id }}_wind_avg"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_wind_avg_ms }}"
      device_class: "wind_speed"
      unit_of_measurement: "m/s"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Wind Direction"
      unique_id: "{{ ws_device_id }}_wind_dir"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_wind_dir_deg }}"
      unit_of_measurement: "째"
      icon: "mdi:compass"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Light"
      unique_id: "{{ ws_device_id }}_light"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_light_lx }}"
      unit_of_measurement: "lx"
      device_class: "illuminance"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "UV Index"
      unique_id: "{{ ws_device_id }}_uv"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_uv }}"
      unit_of_measurement: "UV Index"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Rain"
      unique_id: "{{ ws_device_id }}_rain"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_rain_mm }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Rain Daily"
      unique_id: "{{ ws_device_id }}_rain_daily"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_rain_daily_mm }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Rain Weekly"
      unique_id: "{{ ws_device_id }}_rain_weekly"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_rain_weekly_mm }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Rain Monthly"
      unique_id: "{{ ws_device_id }}_rain_monthly"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_rain_monthly_mm }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Rain 60min"
      unique_id: "{{ ws_device_id }}_rain_hourly"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ws_rain_hourly_mm }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    
    # Soil Sensor
    - name: "Soil Temperature"
      unique_id: "{{ ws_device_id }}_s1_temp"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.soil1_temp_c }}"
      device_class: "temperature"
      unit_of_measurement: "째C"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Soil Moisture"
      unique_id: "{{ ws_device_id }}_s1_humidity"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.soil1_moisture }}"
      device_class: "moisture"
      unit_of_measurement: "%"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Soil Sensor Battery o.k."
      unique_id: "{{ ws_device_id }}_s1_battery"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.status.s1_batt_ok }}"
      device_class: "enum"
      icon: "mdi:battery"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    
    # Lightning Sensor
    - name: "Lightning Distance"
      unique_id: "{{ ws_device_id }}_lgt_distance"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.lgt_ev_dist_km }}"
      device_class: "distance"
      unit_of_measurement: "km"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Lightning Events"
      unique_id: "{{ ws_device_id }}_lgt_ev_events"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.lgt_ev_events }}"
      icon: "mdi:counter"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Lightning Event Time"
      unique_id: "{{ ws_device_id }}_lgt_ev_time"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.lgt_ev_time.time }}"
      device_class: "date"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Lightning Sensor Battery o.k."
      unique_id: "{{ ws_device_id }}_ls_battery"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.status.ls_batt_ok }}"
      device_class: "enum"
      icon: "mdi:battery"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
        
    # BLE Temperature/Humidity Sensor
    - name: "Indoor Temperature"
      unique_id: "{{ ws_device_id }}_ble0_temp"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ble0_temp_c }}"
      device_class: "temperature"
      unit_of_measurement: "째C"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
    - name: "Indoor Humidity"
      unique_id: "{{ ws_device_id }}_ble0_humidity"
      state_topic: *ws_topic
      value_template: "{{ value_json.uplink_message.decoded_payload.bytes.ble0_humidity }}"
      device_class: "moisture"
      unit_of_measurement: "%"
      expire_after: *ws_expiry
      device:
        name: *ws_name
        identifiers: "Bresser"
        manufacturer: "Bresser"
        model: *ws_model
