name: Publish NPM Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install
        working-directory: scripts/bresserweathersensorlw-codec

      - name: Run tests
        run: npm test
        working-directory: scripts/bresserweathersensorlw-codec

      - name: Publish to NPM
        run: npm publish --access public
        working-directory: scripts/bresserweathersensorlw-codec
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
